# Generated by Django 5.0 on 2023-12-13 22:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_user_domain_document_account_delete_documentmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creation_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
