# Generated by Django 5.0 on 2023-12-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_document_creation_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
